### ISSUE TITLE
Compilation issue with boost 1.55.0

### ISSUE THREAD

**Issue by akien-mga** [miki151/keeperrl#567]
Hi,

I'm trying to build the current master branch (btw it would be great if you could tag the alpha13 release), and I'm faced with the following build error:

```
g++ -MMD -Wall -std=c++0x -Wno-sign-compare -Wno-unused-variable -Wfatal-errors -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -g -I. -I./extern -I/usr/include/SFML2  -c view_index.cpp -o obj/view_index.o
In file included from /usr/include/boost/serialization/split_member.hpp:23:0,
                 from /usr/include/boost/serialization/nvp.hpp:33,
                 from /usr/include/boost/serialization/array.hpp:19,
                 from /usr/include/boost/archive/basic_binary_iprimitive.hpp:56,
                 from extern/portable_iarchive.hpp:89,
                 from stdafx.h:53:
/usr/include/boost/serialization/access.hpp: In instantiation of 'static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = eos::portable_iarchive; T = std::array<char, 7ul>]':
/usr/include/boost/serialization/serialization.hpp:69:69:   required from 'void boost::serialization::serialize(Archive&, T&, unsigned int) [with Archive = eos::portable_iarchive; T = std::array<char, 7ul>]'
/usr/include/boost/serialization/serialization.hpp:128:27:   required from 'void boost::serialization::serialize_adl(Archive&, T&, unsigned int) [with Archive = eos::portable_iarchive; T = std::array<char, 7ul>]'
/usr/include/boost/archive/detail/iserializer.hpp:192:5:   required from 'void boost::archive::detail::iserializer<Archive, T>::load_object_data(boost::archive::detail::basic_iarchive&, void*, unsigned int) const [with Archive = eos::portable_iarchive; T = std::array<char, 7ul>]'
/usr/include/boost/archive/detail/iserializer.hpp:120:1:   required from 'class boost::archive::detail::iserializer<eos::portable_iarchive, std::array<char, 7ul> >'
/usr/include/boost/archive/detail/iserializer.hpp:387:13:   required from 'static void boost::archive::detail::load_non_pointer_type<Archive>::load_standard::invoke(Archive&, const T&) [with T = std::array<char, 7ul>; Archive = eos::portable_iarchive]'
/usr/include/boost/archive/detail/iserializer.hpp:439:28:   [ skipping 16 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/common_iarchive.hpp:66:40:   required from 'void boost::archive::detail::common_iarchive<Archive>::load_override(T&, int) [with T = const boost::serialization::nvp<std::array<char, 7ul> >; Archive = eos::portable_iarchive]'
/usr/include/boost/archive/basic_binary_iarchive.hpp:70:7:   required from 'void boost::archive::basic_binary_iarchive<Archive>::load_override(T&, int) [with T = const boost::serialization::nvp<std::array<char, 7ul> >; Archive = eos::portable_iarchive]'
/usr/include/boost/archive/detail/interface_iarchive.hpp:60:9:   required from 'Archive& boost::archive::detail::interface_iarchive<Archive>::operator>>(T&) [with T = const boost::serialization::nvp<std::array<char, 7ul> >; Archive = eos::portable_iarchive]'
/usr/include/boost/archive/detail/interface_iarchive.hpp:67:32:   required from 'Archive& boost::archive::detail::interface_iarchive<Archive>::operator&(T&) [with T = const boost::serialization::nvp<std::array<char, 7ul> >; Archive = eos::portable_iarchive]'
view_index.cpp:24:5:   required from 'void ViewIndex::serialize(Archive&, unsigned int) [with Archive = eos::portable_iarchive]'
view_index.cpp:31:1:   required from here
/usr/include/boost/serialization/access.hpp:118:9: error: 'struct std::array<char, 7ul>' has no member named 'serialize'
         t.serialize(ar, file_version);
         ^
compilation terminated due to -Wfatal-errors.
Makefile:105: recipe for target 'obj/view_index.o' failed
```

Environment:
Mageia 5 64bit, gcc 4.9.2, boost 1.55.0

**Comment by miki151** [comment]
Try using boost 1.56.

**Comment by akien-mga** [comment]
Right, even Fedora Rawhide is still on boost 1.55.0, so that's hardly a solution. But I'll try to compile boost to confirm that the current master is boost > 1.56 only.

**Comment by miki151** [comment]
This compile error might be related to something else, but I'm using some
features that were only added in 1.56.

**Comment by akien-mga** [comment]
I confirm that it builds fine with boost 1.57 (so most likely it would build fine with boost 1.56).
I'd be glad if you can find some fallback implementation of those features for boost 1.55 since I would like to package KeeperRL alpha13 for Mageia 5 (which is due for release in early March, so we probably won't touch boost so late in the release process).
I'd understand if you don't really want to spend time on that though; in such a case, maybe you could point me to the commits that broke compatibility with boost 1.55 so that I can try to adapt them?

**Comment by miki151** [comment]
First try removing the #ifdef/endif condition in lines 315 and 327 to have
array serialization.

Then I think you'll see errors involved with boost::optional.

**Comment by akien-mga** [comment]
I did as you suggested, and it did fix the build of view_index.cpp and brought an error with boost:optional:
```
g++ -MMD -std=c++0x -g -I. -I./extern -I/usr/include/SFML2  -c map_gui.cpp -o obj/map_gui.o
map_gui.cpp: In member function 'void MapGui::updateObjects(const CreatureView*, MapLayout*, bool, bool)':
map_gui.cpp:705:20: error: 'class boost::optional<ViewIndex>' has no member named 'emplace'
       objects[pos].emplace();
                    ^
Makefile:97: recipe for target 'obj/map_gui.o' failed
```
