### ISSUE TITLE
Build failure: collective.h:104:39: error: both 'const' and 'constexpr' cannot be used here

### ISSUE THREAD

**Issue by aapo** [miki151/keeperrl#191]
Trying to compile with gcc-version: (Linaro GCC 4.7-2012.07) 4.7.2 20120701 (prerelease) ends to:

```
In file included from model.cpp:4:0:
collective.h:104:39: error: both 'const' and 'constexpr' cannot be used here
compilation terminated due to -Wfatal-errors.
```

According to this [http://gcc.gnu.org/bugzilla/show_bug.cgi?id=54086] there was bug in gcc. but it is fixed on 4.7.2.

Anyhow, with this I got it pass this file

```
diff --git a/collective.h b/collective.h
index 5b108de..8221034 100644
--- a/collective.h
+++ b/collective.h
@@ -88,7 +88,7 @@ class Collective : public CreatureView, public EventListener {

   enum class Warning { DIGGING, STORAGE, WOOD, LIBRARY, MINIONS, BEDS, TRAINING, WORKSHOP, LABORATORY, GRAVES, CHESTS, MANA, MORE_CHESTS };

-  static constexpr const char* const warningText[] {
+  static constexpr const char* warningText[] {
     "Start digging into the mountain to build a dungeon.",
     "You need to build a storage room.",
     "Cut down some trees for wood",
```
