### PR TITLE
warnings clean up and bits

### PR DESCRIPTION
**Pull request by moozaad**
This is part 1 of my attempt at learning the code base. It includes gcc5 error fix and then also all the unused vars warnings and return types either suppressed or fixed as needed. The make was changed to turn those warnings back on.

You might want to consider not using for(;range()) - it really is just for iterators with begin() and end() and shouldn't be used to replace rand() and for(;;). If you must use it I suggest you make a snippet that includes the suppression as the unused var warnings were hiding other potentially useful vars that had been forgotten about (please review).

The asserts were put in to help detect bad data and assist with return warnings. If you switch to data files for items and creatures etc, they'll be your catch-all if the validation misses errors.

The aim of this is to have a clean compiler output so you never have to go hunting for issues.

### CODE REVIEW

File: collective.cpp [hunk 1]
```diff
@@ -761,7 +761,7 @@ vector<Vec2> Collective::getBedPositions(const vector<PCreature>& creatures, con
   optional<SquareType> bedType = getDormInfo()[spawnType].getBedType();
   vector<Vec2> bedPos;
   for (int i : All(creatures))
-    for (int j : Range(30)) {
+    for (int __attribute__((unused)) j : Range(30)) {
```
Comment (miki151) [inline collective.cpp]: Way too much boilerplate, how about a macro, like this:
for (int UNUSED : Range(30))

File: creature.cpp [hunk 2]
```diff
@@ -1144,6 +1144,8 @@ static string getAttackParam(AttackType type) {
     case AttackType::SPELL: return "spell";
     case AttackType::POSSESS: return "touch";
   }
+  assert("__FUNCTION__ case unknown attack type");
+  return "";
```
Comment (miki151) [inline creature.cpp]: I hate this, even more boilerplate. I use clang during development and it can detect that the switch exhausts all possibilities and doesn't print warnings.

**Comment by miki151** [comment]
I'm not familiar with the review system on github, I added two comments, I
hope you can see them.

In general, I've moved away from gcc, because clang is a way better
compiler (I haven't tried gcc 5 yet though). There are fewer bogus warnings
and it compiles about 40% faster. I only support gcc to able to compile
with Mingw on Windows, and I completely ignore its warnings.

**Comment by miki151** [comment]
Btw, I want to keep full copyright of the code, I hope that's ok.

File: collective.cpp (hunk 1 above)
Comment (moozaad) [inline collective.cpp]: Yeh, I've seen a few around including MSVC compatible ones. At least they it's just a find replace now if that's what you want to do.

File: creature.cpp (hunk 2 above)
Comment (moozaad) [inline creature.cpp]: If you allow modding and/or move your data away from the hard coded approach, you'll need this type of last check.

As is, it is a debug tool as it'll catch edge case errors in your hardcoded definitions as there's no defaults.

**Comment by moozaad** [comment]
> Btw, I want to keep full copyright of the code, I hope that's ok.

I presumed as much.

File: creature.cpp (hunk 2 above)
Comment (miki151) [inline creature.cpp]: That's the whole point, if there no defaults then the compiler will warn if any enum value is omitted in the switch. The assert will never be triggered unless the value is outside the enum range, usually when a variable was uninitialized or there was memory corruption. I don't think checking for these is as important, and if it is, a simple 'FAIL << variable' without the return statement will do.

As for reading from text files, there value is already checked there, see EnumInfo<T>::fromString in util.h line 964

Comment (moozaad) [inline creature.cpp]: True, tbh I forgot C++ did that with case and enums. I just had to go double check the gcc man.  I was mainly focused on palliatively cleaning out the compiler warnings without turning too many off as in my experience, that's always a bad idea.

What version of clang are you using as it doesn't compile on 3.5 here.

Just curious, why the custom FAIL instead of the assert?

Comment (miki151) [inline creature.cpp]: clang -v
Ubuntu clang version 3.5.0-4ubuntu2 (tags/RELEASE_350/final) (based on LLVM
3.5.0)
Target: x86_64-pc-linux-gnu
Thread model: posix

FAIL fails exactly the way I want (at the moment causes a segfault which is
nicely caught in stack_printer.cpp). It also creates a temporary stream, so
I can do FAIL << variable << " " << otherVariable

I don't use assert anywhere in the code, I think.

Comment (moozaad) [inline creature.cpp]: Using clang version 3.5.0 (tags/RELEASE_350/final 216961, 3.5.0-7.1) with libboost 1.57

Gives similar error as https://github.com/miki151/keeperrl/issues/460

In file included from stdafx.h:152:
./serialization.h:288:6: fatal error: redefinition of 'serialize'
void serialize(Archive& ar, std::array<T,N>& a, const unsigned int)
     ^
/usr/include/boost/serialization/array.hpp:145:6: note: previous definition is here
void serialize(Archive& ar, std::array<T,N>& a, const unsigned int /* version */)
     ^

Comment (miki151) [inline creature.cpp]: Damn, this function keeps giving me trouble. On some systems/compilers it's
defined, on others it isn't. If you comment the definition in
serialization.h, that should fix it temporarily.

Comment (moozaad) [inline creature.cpp]: Yeh I tried that before I commented. It gave me a huge cascade errors. I'll come back to it.

Comment (miki151) [inline creature.cpp]: You might have to rm stdafx.h.gch

Comment (moozaad) [inline creature.cpp]: I cleaned before switching compilers so it shouldn't be that. I'll look into it and let you know if there's a fix or if it's a system issue.
